# numpy 

#### numpy array can be either 1 dimensional (vector) or 2 dimensional(matrix)

NumPy (Numerical Python) is a powerful library in Python for numerical computations. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. 


In [98]:
list = [12,13,14]

import numpy as np
# casting 1 dimensional list into NumPy array
np.array(list)

array([12, 13, 14])

In [99]:
my_matx = [[1,2,3],[3,4,5],[5,6,7]]

In [100]:
# casting a list of list into numpy array to get a 2 dimensional matrix
np.array(my_matx)

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

#### NumPy arrays are homogeneous, multi-dimensional collections of elements of the same data type.
*  You can create arrays using various methods:

In [101]:
# From a list
arr1 = np.array([1, 2, 3, 4, 5])

# Specifying data type
arr2 = np.array([1, 2, 3, 4, 5], dtype=float)

# Multi-dimensional array
arr3 = np.array([[1, 2, 3], [4, 5, 6]])

In [102]:
arr1

array([1, 2, 3, 4, 5])

In [103]:
arr2

array([1., 2., 3., 4., 5.])

In [104]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
# Shape of the array
print(arr1.shape)  # Output: (5,)

# Number of dimensions
print(arr2.ndim)  # Output: 1
print(arr3.ndim) 
# Data type
print(arr3.dtype)  # Output: int64

(5,)
1
2
int64


In [106]:
#using Numpy s generation method to create array faster and in a easier way

np.arange(0,111110,10000)

array([     0,  10000,  20000,  30000,  40000,  50000,  60000,  70000,
        80000,  90000, 100000, 110000])

In [107]:
np.arange(0,111110)

array([     0,      1,      2, ..., 111107, 111108, 111109])

In [108]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [109]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [110]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [111]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [112]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [113]:
#np.linspace() to create an array with values that are spaced linearly in a specified interval:

np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [114]:
# with arrange the thrid parameter is the step size
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [115]:
# identify matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [116]:
# Numpy has lots of ways to generate arrays of random numbers
#And this is going to create an array of the given shape you pass in and it's going to populate it with
#random samples from a uniform distribution over 0 to 1.
np.random.rand(9)

array([0.57527906, 0.69140506, 0.18765414, 0.19132875, 0.71554738,
       0.52433407, 0.31108404, 0.44496765, 0.96694326])

In [117]:
np.random.rand(6,3)

array([[0.83520944, 0.99904146, 0.4679412 ],
       [0.66080949, 0.56281261, 0.39262772],
       [0.75330407, 0.02689356, 0.1850006 ],
       [0.39892183, 0.8620586 , 0.25857633],
       [0.62882539, 0.78378254, 0.36922443],
       [0.60677249, 0.52120151, 0.44031832]])

In [118]:
#to return a sample or many samples from the standard normal distribution or a Gaussian
#centered around 0
#try plotting it out to visualize
np.random.randn(9)

array([-0.27345129,  0.02437394, -0.65510074, -0.69017792, -0.44537982,
       -0.53403676, -0.27220506, -0.6790787 , -0.87906397])

In [119]:
# to get a 2 dimensional matrix
intarr= np.random.randn(6,3)

In [120]:
intarr

array([[ 0.70162998, -0.24298786, -1.74031847],
       [ 0.15784565, -1.07241402,  0.69475305],
       [ 0.90729846, -0.25551101, -0.07034263],
       [ 0.09717169, -1.13023472, -1.21612821],
       [-1.44441516,  0.64636051,  0.21654919],
       [ 0.06283839, -0.51904301, -0.16270576]])

In [121]:
#randint returns random integer from low to high number
#lowest inclusive and highest excluive

np.random.randint(3)

0

In [122]:
np.random.randint(1,100)

79

In [123]:
#generate 4 values of random integers from 1 to 100
newarray = np.random.randint(1,100,4)

In [124]:
newarray

array([46, 16, 17, 86])

In [125]:
arr = np.arange(25)

In [126]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [127]:
# reshape array with new dimensions,
# however the number of row times the number of columns should be equal to the total number of items in the array
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [128]:
arr1 = np.arange(36)

In [129]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [130]:
arr1.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [131]:
arr1.reshape(4,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [132]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [133]:
#return max value
arr1.max()

35

In [134]:
#return min value
arr1.min()

0

In [135]:
# argmax gives the location of the max value
newarray.argmax()

3

In [136]:
# argmin gives the location of the max value

newarray.argmin()

1

In [137]:
newarray

array([46, 16, 17, 86])

In [138]:
# shape attribute (not a function)
newarray.shape

(4,)

In [139]:
newarray = newarray.reshape(2,2)

In [140]:
newarray

array([[46, 16],
       [17, 86]])

In [141]:
newarray.shape

(2, 2)

In [142]:
# dtype attribute not a method
newarray.dtype

dtype('int64')

In [143]:
intarr.dtype

dtype('float64')

In [144]:
from numpy.random import randint

In [145]:
randint (2,7)

4

## Indexing in Numpy

#### just like list in python

In [146]:
ar = np.arange(0,10)

In [147]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
#Simplest way to pick out one or some of the elements of an array looks a lot like indexing from a python list.
#using brackets and slice notation
ar[6]

6

In [149]:
ar[:5]

array([0, 1, 2, 3, 4])

#### Slice notation

In [150]:
ar[0:5]

array([0, 1, 2, 3, 4])

In [151]:
ar[5:]

array([5, 6, 7, 8, 9])

In [152]:
ar[5:7]

array([5, 6])

### Numpy arrays differ from normal python list because of their ability to broadcast

In [153]:
ar[0:5] = 11

In [154]:
ar

array([11, 11, 11, 11, 11,  5,  6,  7,  8,  9])

In [155]:
slice_of_array = ar[0:5]

In [156]:
slice_of_array

array([11, 11, 11, 11, 11])

In [157]:
slice_of_array[:] = 22

In [158]:
slice_of_array

array([22, 22, 22, 22, 22])

In [159]:
ar

array([22, 22, 22, 22, 22,  5,  6,  7,  8,  9])

In [160]:
copy_of_array = ar.copy()

In [161]:
copy_of_array

array([22, 22, 22, 22, 22,  5,  6,  7,  8,  9])

In [162]:
copy_of_array[:] = 100

In [163]:
copy_of_array

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [164]:
ar

array([22, 22, 22, 22, 22,  5,  6,  7,  8,  9])

## indexing in matrix

In [165]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [166]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [167]:
#grabbing elements from 2D array

arr_2d[2][1]

8

In [168]:
arr_2d[2,1]

8

In [169]:
arr_2d[0]

array([1, 2, 3])

In [170]:
arr_2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [171]:
arr_2d[2:,2:]

array([[9]])

In [172]:
arr_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [173]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [174]:
arr_2d[1:,0:]

array([[4, 5, 6],
       [7, 8, 9]])

### conditinal selection

In [175]:

arr = np.arange(0,10)

In [176]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [177]:
bool_arr = arr >4

In [178]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [179]:
arr[bool_arr]

array([5, 6, 7, 8, 9])

In [180]:
arr[arr>5]

array([6, 7, 8, 9])

In [181]:
arr[arr<2]

array([0, 1])

In [182]:
arr_2d = np.arange(50).reshape(5,10)

In [183]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [184]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [185]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

## Array operations

* Array with Array
* Array with Scalars
* Universal Array Functions

In [186]:
ary_op = np.arange(0,10)

In [187]:
ary_op

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [188]:
# array with scalar operation
ary_op = ary_op ** 2

In [189]:
ary_op

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [190]:
# array with array operations
ary_op+ary_op

array([  0,   2,   8,  18,  32,  50,  72,  98, 128, 162])

In [191]:
ary_op-ary_op

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [192]:
ary_op

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [193]:
ary_op/ary_op

/var/folders/jw/y0jbb83x57l04gj0jvqk3qm80000gn/T/ipykernel_57562/2427033389.py:1: RuntimeWarning: invalid value encountered in divide
  ary_op/ary_op


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [194]:
1/0

ZeroDivisionError: division by zero

In [ ]:
1/ary_op

### Universal operations

In [ ]:
np.sqrt(ary_op)

In [ ]:
np.exp(ary_op)

In [ ]:
ary_op.dtype


In [ ]:
np.max(ary_op)

In [ ]:
np.sin(ary_op)